"use client";

import { useState } from "react";

interface PromptStreamProps {
  workflow?: string; // e.g. 'real', 'anime' — used to select workflow file on backend
}

export default function PromptStream({ workflow = "real" }: PromptStreamProps) {
  const [prompt, setPrompt] = useState("");
  const [jobId, setJobId] = useState<string | null>(null);
  const [showProgressMessage, setShowProgressMessage] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setJobId(null);
    setShowProgressMessage(false);

    try {
      const res = await fetch("http://localhost:8000/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt, workflow }),
      });
      const data = await res.json();
      setJobId(data.job_id);
      setShowProgressMessage(true);
    } catch (err: any) {
      alert("Error submitting prompt: " + err.message);
    }
  };

  return (
    <div>
      <form onSubmit={handleSubmit}>
        <textarea
          placeholder="Enter prompt…"
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          className="w-full border rounded p-2"
          rows={3}
          required
        />
        <button
          type="submit"
          className="mt-2 w-full bg-blue-600 text-white py-2 rounded"
        >
          Generate
        </button>
      </form>

      {showProgressMessage && (
        <p className="mt-4 text-center text-gray-600">
          <a
            href="http://localhost:8188/task_monitor/index.html"
            className="text-blue-500 underline"
            target="_blank"
            rel="noopener noreferrer"
          >
            View Progress
          </a>
        </p>
      )}

      <div className="mt-4 text-center">
        <p className="mb-2 font-semibold">Resulting Image:</p>
        {jobId ? (
          <img
            src={`http://localhost:8000/image/${jobId}`}
            alt="Generated by ComfyUI"
            className="mx-auto border rounded"
          />
        ) : (
          <p className="text-gray-500">No image generated yet.</p>
        )}
      </div>
    </div>
  );
}
